#!/bin/bash

source "$ENV_PATH"

CURRENT_DATE=$(date +'%Y-%m-%d')

VAR_DATE=${1:-1d}

"$INFLUXTOCSV_PATH" --day "${CURRENT_DATE}" --date "${VAR_DATE}" &>> "${DROPBOXUPLOADLOG_PATH}/dropbox_upload_${CURRENT_DATE}.log"
"$DROPBOXUPLOAD_PATH" --day "${CURRENT_DATE}" --date "${VAR_DATE}" &>> "${DROPBOXUPLOADLOG_PATH}/dropbox_upload_${CURRENT_DATE}.log"