#! /usr/bin/python
# PYTHON_ARGCOMPLETE_OK

"""
Grafana Influx DB Alert Command-line API 
Ma Quantum Group
"""

from dotenv import load_dotenv 
import argcomplete
import requests
import argparse
import time
import json
import os

BLUE = "\033[94m"
LIGHT_BLUE = "\033[38;5;153m"
GREEN = "\033[92m"
RESET = "\033[0m"
Q = "'"

load_dotenv()

grafana_token = os.getenv("GRAPHANA_TOKEN")
grafana_url = os.getenv("GRAFANA_URL")
infludb_url = os.getenv("INFLUXDB_URL")

# Request Headers and Parameters 
provisioning_header = {
    "Content-Type":"application/json",
    "Authorization":f"Bearer {grafana_token}"
}

datasource_header = {
    "Content-Type":"application/json",
    "Application":"application/json",
    "Authorization":f"Bearer {grafana_token}",
    "X-Disable-Provenance":"true"
}

influx_db_get_measurements_parameter = lambda database_name : {
    "db": database_name,
    "q": "SHOW MEASUREMENTS"
}

influxdb_get_fields_parameter = lambda database_name, measurement_name : {
    "db": database_name,
    "q": f"SHOW FIELD KEYS FROM {measurement_name}" 
}

# Influx DB & Grafana Request URLs
alert_rules_url = "api/v1/provisioning/alert-rules/"
dashboard_url = "api/dashboards/uid/"
update_dashboard_url = "api/dashboards/db/"
datasource_url = "api/datasources/"
query_url = "query"
search_url = "api/search/"
folder_url = "api/folders/"

folder_name = os.getenv("ALERT_FOLDER_NAME")
rule_group = os.getenv("EVALUATION_GROUP_NAME")

# Threshold Configuration Class
class ThresholdConfiguration:
    configurations = []

    def __init__(self, file_name):
        self.file_name = file_name
        self.thresholds_config_json = json.load(open(file_name))
        self.alerts_config_json = json.load(open("alerts_config.json"))["alerts"]

    def __str__(self):
        return f"{GREEN}Name:{RESET} {BLUE}{Q+self.getName()+Q:<{20}}{RESET} | {GREEN}File Name:{RESET} {BLUE}{Q+self.file_name+Q:<{30}}{RESET} | {GREEN}Description:{RESET} {BLUE}{self.thresholds_config_json['short-description']}"

    def setAlerts(self):
        for alert in self.thresholds_config_json["alerts"]:
            alert_config = self.alerts_config_json[getJsonArrayIndex("title", self.alerts_config_json, removeDescriptors(alert["title"]))[0]]

            if (threshold := Threshold.getThresholdFromName(alert["title"], False)) is not None:
                if threshold.getThreshold() != alert["threshold"]:
                    threshold.changeDashboardThreshold(alert["threshold"])
                if threshold.getStateString() != alert["state"]:
                    threshold.changeDashboardThresholdState(alert["state"])
                    
            else:
                boundType = "lt" if "Lower" in alert["title"] else "gt"
                alertType = "Critical" if "Critical" in alert["title"] else "Warning"
                Threshold.createAlert(alert["threshold"], alert["state"], boundType, alertType, alert_config)
        
        for threshold in Threshold.thresholds:
            if not getJsonArrayIndex("title", self.thresholds_config_json["alerts"], threshold.getName(), True):
                Threshold.delete(threshold)

    def getName(self):
        return self.thresholds_config_json["name"]
    
    @staticmethod
    def getConfigFromName(name):
        result = None
        for config in ThresholdConfiguration.configurations:
            if name in config.getName():
                result = config
                break
        return result

class Threshold:
    thresholds  = []

    def __init__(self, alertJson):
        self.alertJson = alertJson

    def __str__(self): # Prints status of threshold to command line
        if self.getStateString() == "ON":
            BLUE_COLOR = BLUE
        else:
            BLUE_COLOR = LIGHT_BLUE
        return f"{GREEN}Name:{RESET} {BLUE_COLOR}{Q+self.getName()+Q:<{50}}{RESET} | {GREEN}Threshold:{RESET} {BLUE_COLOR}{self.getAlertType()+str(self.getThreshold()):<{25}}{RESET} | {GREEN}State:{RESET} {BLUE_COLOR}{self.getStateString()}{RESET}"

    def getName(self): # Returns title of alert
        return self.alertJson["title"] 

    def getThreshold(self): # Returns numerical value of alert
        return self.alertJson["data"][2]["model"]["conditions"][0]["evaluator"]["params"][0]

    def getStateString(self): # Return state of alert
        return "OFF" if bool(self.alertJson["isPaused"]) else "ON"

    def getAnnotatedDashboardUid(self): # returns uid of dashboard associated with alert
        return self.alertJson["annotations"]["__dashboardUid__"]

    def getAlertId(self): # Returns alert uid
        return self.alertJson["uid"]
    
    def getAlertType(self): # Returns alert type
        c_refId_index = getJsonArrayIndex("refId", self.alertJson["data"], "C")[0]
        bound_type = self.alertJson["data"][c_refId_index]["model"]["conditions"][0]["evaluator"]["type"]
        return "Greater than " if bound_type == "gt" else "Less than "
    
    def getDatasourceUid(self): # Returns the uid of the Data source, i.e. which Influx DB database 
        return self.alertJson["data"][getJsonArrayIndex("refId", self.alertJson["data"], "A")[0]]["datasourceUid"]

    def getMeasurement(self): # Returns name of measurement from Influx DB database
        return self.alertJson["data"][getJsonArrayIndex("refId", self.alertJson["data"], "A")[0]]["model"]["measurement"]
    
    def getField(self): # Returns name of Field from Influx DB measurement
        a_refId_index = getJsonArrayIndex("refId", self.alertJson["data"], "A")[0]
        field_type_index = getJsonArrayIndex("type", self.alertJson["data"][a_refId_index]["model"]["select"][0], "field")[0]
        return self.alertJson["data"][a_refId_index]["model"]["select"][0][field_type_index]["params"][0]
    
    def getAllMatchingDashboardPanels(self): # Returns tuple list of dashboard uid and associated panel index (NOT panel id)
        dashboardPanels = []
        for dashboard in Threshold.getDashboards().values():
            for index, panel in enumerate(httpGetRequest(grafana_url+dashboard_url+dashboard, provisioning_header)["dashboard"]["panels"]):
                if self.checkPanelMatch(panel):
                    dashboardPanels.append((dashboard, index))
    
        return dashboardPanels
    
    def checkPanelMatch(self, panel): # Checks to see if datasource parameters match for a dashboard panel
        return panel["targets"][0]["datasource"]["uid"] == self.getDatasourceUid() \
            and panel["targets"][0]["measurement"] == self.getMeasurement() \
            and panel["targets"][0]["select"][0][getJsonArrayIndex("type", panel["targets"][0]["select"][0], "field")[0]]["params"][0] == self.getField()        

    def createDashboardThreshold(self): # Create threshold in dashboard from alertJson value, shift other values if required
        for dashboardUid, panelNum in self.getAllMatchingDashboardPanels():

            dashboardJson = httpGetRequest(grafana_url+dashboard_url+dashboardUid, provisioning_header)
            color_indices = lambda color : getJsonArrayIndex("color", dashboardJson["dashboard"]["panels"][panelNum]["fieldConfig"]["defaults"]["thresholds"]["steps"], color)
            
            value = self.getThreshold()
            current_values = [item.get('value', None) for item in dashboardJson["dashboard"]["panels"][panelNum]["fieldConfig"]["defaults"]["thresholds"]["steps"]]
            index = next((i for i, v in enumerate(current_values) if v is not None and value < v), len(current_values))

            if "Upper" in self.getName():
                if "Warning" in self.getName():
                    dashboardJson["dashboard"]["panels"][panelNum]["fieldConfig"]["defaults"]["thresholds"]["steps"].insert(index, {"color":"orange", "value":value})                    
                else:
                    dashboardJson["dashboard"]["panels"][panelNum]["fieldConfig"]["defaults"]["thresholds"]["steps"].insert(index, {"color":"red", "value":value})
            else:
                if "Warning" in self.getName():
                    dashboardJson["dashboard"]["panels"][panelNum]["fieldConfig"]["defaults"]["thresholds"]["steps"][color_indices("green")[0]]["color"] = "dark-orange"
                    dashboardJson["dashboard"]["panels"][panelNum]["fieldConfig"]["defaults"]["thresholds"]["steps"].insert(index, {"color":"green", "value":value})
                else:
                    if getJsonArrayIndex("color", dashboardJson["dashboard"]["panels"][panelNum]["fieldConfig"]["defaults"]["thresholds"]["steps"], "dark-orange", True):
                        dashboardJson["dashboard"]["panels"][panelNum]["fieldConfig"]["defaults"]["thresholds"]["steps"][color_indices("dark-orange")[0]]["color"] = "dark-red"
                        dashboardJson["dashboard"]["panels"][panelNum]["fieldConfig"]["defaults"]["thresholds"]["steps"].insert(index, {"color":"dark-orange", "value":value})
                    else:
                        dashboardJson["dashboard"]["panels"][panelNum]["fieldConfig"]["defaults"]["thresholds"]["steps"][color_indices("green")[0]]["color"] = "dark-red"
                        dashboardJson["dashboard"]["panels"][panelNum]["fieldConfig"]["defaults"]["thresholds"]["steps"].insert(index, {"color":"green", "value":value})

            if dashboardJson["dashboard"]["panels"][panelNum]["type"] == "timeseries":
                dashboardJson["dashboard"]["panels"][panelNum]["fieldConfig"]["defaults"]["custom"]["thresholdsStyle"]["mode"] = "area"
            
            httpPostRequest(grafana_url+update_dashboard_url, dashboardJson)
        
    def removeDashboardThreshold(self): # Delete threshold in dashboard, shift other values if required 
        for dashboardUid, panelNum in self.getAllMatchingDashboardPanels():
            dashboardJson = httpGetRequest(grafana_url+dashboard_url+dashboardUid, provisioning_header)
            color_indices = lambda color : getJsonArrayIndex("color", dashboardJson["dashboard"]["panels"][panelNum]["fieldConfig"]["defaults"]["thresholds"]["steps"], color)

            if "Upper" in self.getName():
                dashboardJson["dashboard"]["panels"][panelNum]["fieldConfig"]["defaults"]["thresholds"]["steps"].pop(color_indices("orange" if "Warning" in self.getName() else "red")[0])                    
            else:
                if "Warning" in self.getName():
                    dashboardJson["dashboard"]["panels"][panelNum]["fieldConfig"]["defaults"]["thresholds"]["steps"].pop(color_indices("green")[0])
                    dashboardJson["dashboard"]["panels"][panelNum]["fieldConfig"]["defaults"]["thresholds"]["steps"][color_indices("dark-orange")[0]]["color"] = "green"
                else:
                    if getJsonArrayIndex("color", dashboardJson["dashboard"]["panels"][panelNum]["fieldConfig"]["defaults"]["thresholds"]["steps"], "dark-orange", True):
                        dashboardJson["dashboard"]["panels"][panelNum]["fieldConfig"]["defaults"]["thresholds"]["steps"].pop(color_indices("dark-orange")[0])
                        dashboardJson["dashboard"]["panels"][panelNum]["fieldConfig"]["defaults"]["thresholds"]["steps"][color_indices("dark-red")[0]]["color"] = "dark-orange"
                    else:
                        dashboardJson["dashboard"]["panels"][panelNum]["fieldConfig"]["defaults"]["thresholds"]["steps"].pop(color_indices("green")[0])
                        dashboardJson["dashboard"]["panels"][panelNum]["fieldConfig"]["defaults"]["thresholds"]["steps"][color_indices("dark-red")[0]]["color"] = "green"

            httpPostRequest(grafana_url+update_dashboard_url, dashboardJson)
        
    def changeDashboardThreshold(self, value): # Change the value of the dashboard threshold, if editAlertJson == False edit only panel 
        c_refId_index = getJsonArrayIndex("refId", self.alertJson["data"], "C")[0]
        self.alertJson["data"][c_refId_index]["model"]["conditions"][0]["evaluator"]["params"][0] = value
        httpPutRequest(grafana_url+alert_rules_url+self.getAlertId(), self.alertJson)

        if self.getStateString() == "OFF":
            return

        for dashboardUid, panelNum in self.getAllMatchingDashboardPanels():
            thresholdNum = None
            dashboardJson = httpGetRequest(grafana_url+dashboard_url+dashboardUid, provisioning_header)

            color_indices = lambda color : getJsonArrayIndex("color", dashboardJson["dashboard"]["panels"][panelNum]["fieldConfig"]["defaults"]["thresholds"]["steps"], color)

            if "Warning" in self.getName() and "Upper" in self.getName():
                thresholdNum = color_indices("orange")[0]
            elif "Critical" in self.getName() and "Upper" in self.getName():
                thresholdNum = color_indices("red")[0]
            elif "Warning" in self.getName() and "Lower" in self.getName():
                thresholdNum = color_indices("green")[0]
            elif "Critical" in self.getName() and "Lower" in self.getName():
                if getJsonArrayIndex("color", dashboardJson["dashboard"]["panels"][panelNum]["fieldConfig"]["defaults"]["thresholds"]["steps"], "dark-orange", True):
                    thresholdNum = color_indices("dark-orange")[0]
                else:
                    thresholdNum = color_indices("green")[0]

            dashboardJson["dashboard"]["panels"][panelNum]["fieldConfig"]["defaults"]["thresholds"]["steps"][thresholdNum]["value"] = value

            httpPostRequest(grafana_url+update_dashboard_url, dashboardJson)

    def changeDashboardThresholdState(self, state): # Sets the state of the dashboard's threshold
        if self.getStateString() == state:
            return
        if state == "ON":
            self.alertJson["isPaused"] = bool(False)
            self.createDashboardThreshold()
        else:
            self.alertJson["isPaused"] = bool(True)
            self.removeDashboardThreshold()

        httpPutRequest(grafana_url+alert_rules_url+self.getAlertId(), self.alertJson)

    @staticmethod
    def createAlert(threshold, state, bound_type, alert_type, inputJson=None):
        if inputJson is None:
            print(f"Creating alert ... Enter in values below:")

        databases = {database["jsonData"]["dbName"]:database["uid"] for database in httpGetRequest(grafana_url+datasource_url, datasource_header)}
        if inputJson is None:
            database = Threshold.getCheck("Influx DB databases", list(databases.keys()))
        else:
            database = inputJson["database"]

        measurements = [measurement[0] for measurement in httpGetRequest(infludb_url+query_url, None, influx_db_get_measurements_parameter(database))["results"][0]["series"][0]["values"]]
        if inputJson is None:
            measurement = Threshold.getCheck(f"Measurement from database {database}", measurements)
        else:
            measurement = inputJson["measurement"]

        fields = [field[0] for field in httpGetRequest(infludb_url+query_url, None, influxdb_get_fields_parameter(database, measurement))["results"][0]["series"][0]["values"]]
        if inputJson is None:
            field = Threshold.getCheck(f"field from measurement {measurement}", fields)
        else:
            field = inputJson["field"]

        with open('alert_template.json', 'r') as file:
            alert_template = json.load(file)

            alert_template["ruleGroup"] = rule_group

            folders = httpGetRequest(grafana_url+folder_url, provisioning_header)
            alert_template["folderUID"] = folders[getJsonArrayIndex("title", folders, folder_name)[0]]["uid"]
            
            if inputJson is None:
                alert_template["title"] = input("Enter name: ") + (" Upper " if bound_type == "gt" else " Lower ") + alert_type + " Alert" 
            else:
                alert_template["title"] = inputJson["title"] + (" Upper " if bound_type == "gt" else " Lower ") + alert_type + " Alert" 

            a_refId_index = getJsonArrayIndex("refId", alert_template["data"], "A")[0]
            c_refId_index = getJsonArrayIndex("refId", alert_template["data"], "C")[0]

            alert_template["data"][a_refId_index]["datasourceUid"] = databases[database]
            alert_template["data"][a_refId_index]["model"]["datasource"]["uid"] = databases[database]
            alert_template["data"][a_refId_index]["model"]["measurement"] = measurement

            field_type_index = getJsonArrayIndex("type", alert_template["data"][a_refId_index]["model"]["select"][0], "field")[0]
            alert_template["data"][a_refId_index]["model"]["select"][0][field_type_index]["params"][0] = field

            alert_template["data"][c_refId_index]["model"]["conditions"][0]["evaluator"]["params"].append(threshold)
            alert_template["data"][c_refId_index]["model"]["conditions"][0]["evaluator"]["type"] = bound_type

            alert_template["labels"]["level"] = alert_type.lower()
            
            if inputJson is None:
                alert_template["noDataState"] = strictInput("State alert when NO DATA? ('OK'/'Alerting') ", ["OK", "Alerting"])
            else:
                alert_template["noDataState"] = inputJson["nodata"]

            dashboards = Threshold.getDashboards()
            if inputJson and "dashboardname" in inputJson:
                alert_template["annotations"]["__dashboardUid__"] = dashboards[inputJson["dashboardname"]]
                panelId = None

                for panel in httpGetRequest(grafana_url+dashboard_url+dashboards[inputJson["dashboardname"]], provisioning_header)["dashboard"]["panels"]:
                    if Threshold.checkPanelMatchToJson(panel, databases[database], measurement, field):
                        panelId = panel["id"]
                        break

                if panelId == None:
                    raise Exception(f"No matching panels for {inputJson['title']}")
                alert_template["annotations"]["__panelId__"] = str(panelId)

            elif inputJson is None and strictInput("Configure dashboard-alert pair? ('y'/'n') ", ["y", "n"]) == "y":
                dashboardUid = dashboards[Threshold.getCheck("dashboard names", list(dashboards.keys()))]
                panels = Threshold.getPanels(dashboardUid, "timeseries")
                alert_template["annotations"]["__dashboardUid__"] = dashboardUid
                alert_template["annotations"]["__panelId__"] = str(panels[Threshold.getCheck("timeseries panel names", list(panels.keys()))])
                
            alert_template["isPaused"] = bool(False) if state == "ON" else bool(True)
            alert = Threshold(alert_template)
            if state == "ON":
                alert.createDashboardThreshold()
            
            httpPostRequest(grafana_url+alert_rules_url, alert_template, datasource_header)
            
            Threshold.thresholds.append(alert)         
            return alert
        
    @staticmethod
    def delete(threshold): # Deletes dashboard thresholds, alert from api, etc.
        if threshold.getStateString() == "ON":
            threshold.removeDashboardThreshold()
        httpDeleteRequest(grafana_url+alert_rules_url+threshold.getAlertId())
        Threshold.thresholds.pop(Threshold.getThresholdFromName(threshold.getName(), False, True)[0])
        
    @staticmethod
    def getThresholdFromName(name, multipleThresholds, indices=False):
        result = []
        for index, threshold in enumerate(Threshold.thresholds):
            if name in threshold.getName():
                if indices:
                    result.append((index, threshold))
                else:
                    result.append(threshold)

        if result == []:
            return None
        return result if multipleThresholds else result[0]
    
    @staticmethod
    def getDashboards(): # Gets all dashboards on grafana 
        dashboardUids = {}
        for dashboard in httpGetRequest(grafana_url+search_url, provisioning_header):
            if dashboard["type"] != "dash-db":
                continue
            dashboardUids[dashboard["title"]] = dashboard["uid"]

        return dashboardUids
    
    @staticmethod
    def getPanels(dashboardUid, type=None): # Gets all panel names and respective id's from dashboard
        panelIds = {}   
        for panel in httpGetRequest(grafana_url+dashboard_url+dashboardUid, provisioning_header)["dashboard"]["panels"]:
            if type and panel["type"] != type:
                continue
            panelIds[panel["title"]] = panel["id"]

        return panelIds
    
    @staticmethod
    def checkPanelMatchToJson(panelJson, datasourceUid, measurement, field):
        return panelJson["targets"][0]["datasource"]["uid"] == datasourceUid \
            and panelJson["targets"][0]["measurement"] == measurement \
            and panelJson["targets"][0]["select"][0][getJsonArrayIndex("type", panelJson["targets"][0]["select"][0], "field")[0]]["params"][0] == field
    
    @staticmethod
    def getCheck(parameterName, parameters):
        print(f"Choose {parameterName}, or number from list:")
        print("\n".join(f"{index}. {parameter}" for index, parameter in enumerate(parameters)))
        
        parameter = input("Name or Index: ")

        while True:
            if parameter in parameters:
                return parameter
            elif parameter.isdigit() and int(parameter) < len(parameters) and int(parameter) >= 0:
                return parameters[int(parameter)]
            else:
                parameter = input(f"'{parameter}' not in {parameterName} list or in range of possible indexes, retry: ")

def httpGetRequest(url, header, param=None):
    request = requests.get(url, headers=header, params=param)
    if request.status_code != 200:
        print(f"Error in request GET: {json.dumps(request.json())}")
        time.sleep(2)
        return httpGetRequest(url, header, param)
    return request.json()

def httpPutRequest(url, jsonMessage, header=provisioning_header):
    request = requests.put(url, data=json.dumps(jsonMessage), headers=header)
    if request.status_code != 200:
        print(f"Error in request PUT: {json.dumps(request.json())}")
        time.sleep(2)
        httpPutRequest(url, jsonMessage, provisioning_header)

def httpPostRequest(url, jsonMessage, header=provisioning_header):
    request = requests.post(url, data=json.dumps(jsonMessage), headers=header)
    if request.status_code != 200 and request.status_code != 201:
        print(f"Error in request POST: {json.dumps(request.json())}")
        time.sleep(2)
        httpPostRequest(url, jsonMessage, provisioning_header)

def httpDeleteRequest(url, header=datasource_header):
    header.pop("X-Disable-Provenance", None)
    request = requests.delete(url, headers=header)
    if request.status_code != 204:
        print(f"Error in request DELETE: {json.dumps(request.json())}")
        time.sleep(2)
        httpDeleteRequest(url)

def strictInput(question, correctValues):
    while True:
        answer = input(question)
        if answer in correctValues:
            return answer
        else:
            print(f"Incorrect value: {answer}, enter correct value: '{', '.join(correctValues)}'")

def removeDescriptors(string):
    return string.replace("Warning", "").replace("Critical", "").replace("Upper", "").replace("Lower", "").replace("Alert", "").rstrip()

def getJsonArrayIndex(subfield, json, value, empty=False):
        arrIndices = []
        for index, subJson in enumerate(json):
            if value == subJson[subfield]:
                arrIndices.append(index)
                break

        if len(arrIndices) == 0 and not empty:
            raise Exception(f"{value} is not found in Json Array {json}")
        return arrIndices
    
def getArguments():
    parser = argparse.ArgumentParser(description='edit and view threshold values')
    configuration_names = [configuration.getName() for configuration in ThresholdConfiguration.configurations]

    parser.add_argument("--name", default=None, type=str, help="enter EXACT threshold name, to view names run program w/o arguments")
    parser.add_argument("--threshold", default=None, type=float, help="float value for threshold")
    parser.add_argument("--state", choices=["ON", "OFF"], default=None, type=str, help="'ON' or 'OFF'")

    parser.add_argument("--create_upper_critical", action="store_true", help="create critical upper bound alert")
    parser.add_argument("--create_lower_critical", action="store_true", help="create critical lower bound alert")
    parser.add_argument("--create_upper_warning", action="store_true", help="create warning upper bound alert")
    parser.add_argument("--create_lower_warning", action="store_true", help="create warning lower bound alert")
    parser.add_argument("--delete", default=None, type=str, help="delete alert")

    parser.add_argument("--config", choices=configuration_names, default=None, type=str, help="alert configurations")

    argcomplete.autocomplete(parser)

    return parser.parse_args()

if __name__ == "__main__":
    alerts = httpGetRequest(grafana_url+alert_rules_url, provisioning_header)

    os.chdir(os.path.dirname(os.path.abspath(__file__)))

    for file_name in os.listdir(os.path.dirname(os.path.abspath(__file__))):
        if file_name.endswith("config.json") and file_name != "alerts_config.json":
            ThresholdConfiguration.configurations.append(ThresholdConfiguration(file_name))

    for alert in alerts:
        Threshold.thresholds.append(Threshold(alert))

    arguments = getArguments()

    if arguments.config:
        if (config := ThresholdConfiguration.getConfigFromName(arguments.config)) is not None:
            config.setAlerts()

    if sum([arguments.create_upper_critical, arguments.create_upper_warning, arguments.create_lower_critical, arguments.create_lower_warning]) == 1 and arguments.threshold is not None and arguments.state is not None:
        if arguments.create_upper_critical:                
            Threshold.thresholds.append(Threshold.createAlert(arguments.threshold, arguments.state, "gt", "Critical"))
        elif arguments.create_lower_critical:
            Threshold.thresholds.append(Threshold.createAlert(arguments.threshold, arguments.state, "lt", "Critical"))
        elif arguments.create_upper_warning:
            Threshold.thresholds.append(Threshold.createAlert(arguments.threshold, arguments.state, "gt", "Warning"))
        else:
            Threshold.thresholds.append(Threshold.createAlert(arguments.threshold, arguments.state, "lt", "Warning"))
        
    if arguments.delete and (arguments.delete == "*" or Threshold.getThresholdFromName(arguments.delete, False) is not None):
        if arguments.delete == "*":
            if strictInput(f"Are you sure you want to delete all {len(Threshold.thresholds)} alerts! It is irreversible!!! (Yes/n) ", ["Yes", "n"]) == "Yes":
                for threshold in Threshold.thresholds[::-1]:
                     Threshold.delete(threshold)

        elif strictInput(f"Are you sure you want to delete: '{arguments.delete}'? It is irreversible! (Y/n) ", ["Y", "n"]) == "Y":
            for index in range(len(Threshold.thresholds) - 1, -1, -1):
                if arguments.delete in Threshold.thresholds[index].getName():
                    Threshold.delete(Threshold.thresholds[index])
            
    if arguments.name is not None:
        if arguments.threshold is not None and arguments.state is not None:
            raise Exception("Edit one property per request")

        if arguments.threshold is not None:
            Threshold.getThresholdFromName(arguments.name, False).changeDashboardThreshold(arguments.threshold)

        if arguments.state is not None:
            thresholds = Threshold.getThresholdFromName(arguments.name, True)
            for threshold in thresholds:
                threshold.changeDashboardThresholdState(arguments.state)

    print(f"{GREEN}----------- Configurations -----------{RESET}")
    for config in ThresholdConfiguration.configurations:
        print(config)

    print(f"{GREEN}-----------     Alerts     -----------{RESET}")
    for enum, threshold in enumerate(httpGetRequest(grafana_url+alert_rules_url, provisioning_header)):
        Threshold.thresholds[enum] = Threshold(threshold)
        print(Threshold(threshold))