#! /usr/bin/python

from dotenv import load_dotenv 
import argparse
import requests
import os

load_dotenv()

contact_points_url = os.getenv("GRAFANA_URL")+"/api/v1/provisioning/contact-points"

header = {

}

if __name__ == "__main__":
    uid = requests.get(, )